favicon: null
name: DrKevinSkinner
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1715433
  brandStrength: 0.7361344806849957
  lightness: 0.7437276
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.9856248
typography_spectrum: 0.2177304669748992
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3867577621713281
analytics:
  twitter: null
  google: null
  facebook: null
